### PR TITLE
Create eboard only votes

### PR DESCRIPTION
**Pull request by mxmeinhold**
Add a major project and eboard only vote that limit authentication to eboard.                                                                     
                                                                          
To assist eboard in doing major projects, vote needs to support votes that only eboard can participate in, which this PR looks to implement.           
                                                                          
Open questions:                                                                                                                                   
- [ ] Should creation still be limited to only evals, or expanded to eboard overall?                                                                    
                                                                          
This is a work in progress. Hopes are to have it done and deployed prior to eboard meeting wednesday. 

## TODOs
- [x] Server side permissions and filtering
- [ ] New create page?

### CODE REVIEW

**Comment by mxmeinhold** [comment]
@EricKarschner37 @VivianNK Thoughts on the following create page (perhaps not part of this PR, we'll see)
```markdown
## Poll Title
Text input

## Poll Options
- Pass, Fail, Abstain
- Pass, Fail or Conditional, Abstain
- Conditional, Fail, Abstain
- Yes, No, Abstain
- Custom options (e.g. conditional, informal poll)

### Custom options (if custom options selected)
Text input like it currently is

## Poll Permissions
- Voting only
- Eboard only
- Hidden Eboard only (not visible to members)

## Vote Visibility
- Secret (see only aggregate vote counts)
- Open (see who voted for what)
```

**Comment by mxmeinhold** [comment]
Also @EricKarschner37 I marked this as draft so you don't merge it ahead of time.

**Comment by mxmeinhold** [comment]
@EricKarschner37 How do you want to handle filtering the vote list? Server side?

We also need to set up loading all pending votes from the db.

**Comment by EricKarschner37** [comment]
> 
> 
> @EricKarschner37 How do you want to handle filtering the vote list? Server side?

Yeah I think that's best, if there's a _very_ sensitive vote that only eboard should see, server side seems the safest

**Comment by mxmeinhold** [comment]
Would you add that to the list route?

I think we should also add a way for the frontend to skip you to just seeing the results if you can't vote in a poll.

**Comment by mxmeinhold** [comment]
@VivianNK we need to do review and some testing today, so that we can deploy this by evening. We should be mostly set :tm:

**Comment by mxmeinhold** [comment]
Alright, I think we've cleared the testing on vote.cs.house and local. Once I get stamps, I'll squash the last fixup and :ship:.

**Review by EricKarschner37 — APPROVED** [review]
Lgtm

**Comment by mxmeinhold** [comment]
Alright, I'm yeeting, and we can fixup after it's merged if @VivianNK has comments.

**Pull request merged**
